on:
  schedule:
    - cron: '55 23 * * Sat'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Install python test dependency
        shell: bash
        run: pip install pytest pytest-asyncio
      - name: Run ch.py test cases
        shell: bash
        env:
          CHPYBOT_PASSWORD: ${{ secrets.CHPYBOT_PASSWORD }}
          CHPYBOT_USER: ${{ secrets.CHPYBOT_USER }}
        run: python -m pytest ch
